name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/CODE_OF_CONDUCT.md
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - .github/FUNDING.yml
      - LICENSE
      - .gitignore
  pull_request:
    paths-ignore:
      - .github/CODE_OF_CONDUCT.md
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - .github/FUNDING.yml
      - LICENSE
      - .gitignore
  schedule:
    - cron: "0 5 * * 1,3,6"

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
#  RUSTFLAGS: --deny warnings

jobs:
  test:
    name: Rust ${{matrix.toolchain}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
#          - nightly
#          - 1.60.0
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make target dir
        run: mkdir target
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: v0-cargo-test-${{runner.os}}-${{steps.toolchain.outputs.cachekey}}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            v0-cargo-lint-${{runner.os}}-${{steps.toolchain.outputs.cachekey}}-${{ hashFiles('**/Cargo.lock') }}
            v0-cargo-test-${{runner.os}}-${{steps.toolchain.outputs.cachekey}}-
      - name: Install toktx
        uses: ./.github/actions/install-toktx
      - name: Init toolchain
        uses: dtolnay/rust-toolchain@v1
        id: toolchain
        with:
          toolchain: ${{matrix.toolchain}}
      - name: ls
        continue-on-error: true
        run: ls
      - name: toktx --help
        continue-on-error: true
        run: toktx --help
#      - name: Build
#        run: cargo build --workspace --tests --all-features --locked
#      - name: Test
#        run: cargo test --workspace --all-features --locked
